language: csharp  
mono: none
dotnet: 2.0.0
dist: trusty
sudo: false
solution: CachedRepository.sln

script: 
- dotnet restore
- dotnet build
- dotnet test Example.API.Tests/Example.API.Tests.csproj
- dotnet test Example.Repositories.Tests/Example.Repositories.Tests.csproj
- dotnet test Example.Services.Tests/Example.Services.Tests.csproj
